<a href="https://colab.research.google.com/github/vichacker1234/Vicstatistics/blob/main/notebooks/01_data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Caso Técnico: Sistema de Análisis Inteligente para Operaciones Rappi**

# Procesamiento de los datos
## Sistema de Análisis Inteligente para Operaciones

Este notebook realiza el procesamiento y limpieza de datos operacionales para preparar la información utilizada por el sistema de insights automáticos y el bot conversacional.

In [1]:
# Crear estructura del proyecto (solo primera vez)
!mkdir -p data/raw data/processed src

# **1. Cargar las librerías para el procesamiento de datos**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

# **2. Cargar los datasets**

In [3]:
## Datafrane de las métricas
df_metricas_input=pd.read_excel('/content/Sistema de Análisis Inteligente para Operaciones Rappi - Dummy Data (2).xlsx',sheet_name='RAW_INPUT_METRICS')
# parte superior de la base de métricas
df_metricas_input.head()

,COUNTRY,CITY,ZONE,ZONE_TYPE,ZONE_PRIORITIZATION,METRIC,L8W_ROLL,L7W_ROLL,L6W_ROLL,L5W_ROLL,L4W_ROLL,L3W_ROLL,L2W_ROLL,L1W_ROLL,L0W_ROLL
0,EC,Quito,San Martin de Porras,Non Wealthy,Not Prioritized,Retail SST > SS CVR,0.602339,0.538596,0.657760,0.709402,0.781532,0.731758,0.676429,0.670137,0.735549
1,BR,Bauru,FS Parque Jardim Europa/Vila Riachuelo - BAU,Non Wealthy,Not Prioritized,Restaurants SST > SS CVR,0.857544,0.926667,0.880000,0.525000,0.450000,0.425000,0.250000,0.450000,0.475000
2,MX,Mexicali,MXL_Universidad,Wealthy,Prioritized,Retail SST > SS CVR,0.900823,0.904237,0.905766,0.900928,0.895019,0.888999,0.894802,0.897732,0.897864
3,CL,Santiago De Chile,Colina,Non Wealthy,Not Prioritized,Retail SST > SS CVR,0.798946,0.770919,0.772061,0.784609,0.799962,0.804492,0.737508,0.733916,0.741457
4,MX,Guadalajara,Valle Real,Wealthy,High Priority,Gross Profit UE,3.914477,3.827934,3.534116,3.486583,3.632156,3.473549,3.541963,3.808373,3.780534

In [4]:
# dataset de las órdenes
df_raw_orders=pd.read_excel('/content/Sistema de Análisis Inteligente para Operaciones Rappi - Dummy Data (2).xlsx',sheet_name='RAW_ORDERS')
# Parte superior de las órdenes
df_raw_orders.head()

,COUNTRY,CITY,ZONE,METRIC,L8W,L7W,L6W,L5W,L4W,L3W,L2W,L1W,L0W
0,CO,Bogota,Chapinero,Orders,264650.0,261767.0,277005.0,279886.0,277954.0,275344.0,275633.0,279048.0,274376.0
1,CO,Bogota,Usaquén,Orders,233674.0,224436.0,241602.0,240411.0,240786.0,236591.0,241475.0,238649.0,236876.0
2,PE,Lima,Miraflores,Orders,123252.0,125820.0,126245.0,123770.0,126467.0,124376.0,124751.0,123431.0,124757.0
3,CO,Medellin,Poblado_guayabal,Orders,123163.0,118244.0,124015.0,108165.0,106785.0,117266.0,120384.0,121428.0,117824.0
4,PE,Lima,San isidro,Orders,109987.0,114369.0,114077.0,113302.0,115501.0,113639.0,113772.0,112622.0,114141.0

In [6]:
print("Las dimensiones de la base de métricas es:", df_metricas_input.shape)
print("Las dimensiones de la base de órdenes es:", df_raw_orders.shape)

Las dimensiones de la base de métricas es: (12573, 15)
Las dimensiones de la base de órdenes es: (1242, 13)

# **3. Análisis descriptivo y exploratiorio de las bases**

In [11]:
## información general de la naturaleza de los campos de la base relacionada con las métricas
df_metricas_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12573 entries, 0 to 12572
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   COUNTRY              12573 non-null  object
 1   CITY                 12573 non-null  object
 2   ZONE                 12573 non-null  object
 3   ZONE_TYPE            12573 non-null  object
 4   ZONE_PRIORITIZATION  12573 non-null  object
 5   METRIC               12573 non-null  object
 6   L8W_ROLL             12460 non-null  float64
 7   L7W_ROLL             12466 non-null  float64
 8   L6W_ROLL             12462 non-null  float64
 9   L5W_ROLL             12467 non-null  float64
 10  L4W_ROLL             12475 non-null  float64
 11  L3W_ROLL             12501 non-null  float64
 12  L2W_ROLL             12518 non-null  float64
 13  L1W_ROLL             12530 non-null  float64
 14  L0W_ROLL             12573 non-null  float64
dtypes: float64(9), object(6)
memory usage: 1.4+ MB

Se detectaron errores de tipado en las variables cualitativas detalladas a continuación. Es necesario realizar la conversión de ?'string' a 'category' para reflejar correctamente su naturaleza:

* COUNTRY          
* CITY          
* ZONE               
* ZONE_TYPE           
* ZONE_PRIORITIZATION   
* METRIC

In [10]:
## información general de la naturaleza de los campos de la base relacionada con las órdenes
df_raw_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1242 entries, 0 to 1241
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   COUNTRY  1242 non-null   object
 1   CITY     1242 non-null   object
 2   ZONE     1242 non-null   object
 3   METRIC   1242 non-null   object
 4   L8W      1021 non-null   float64
 5   L7W      1022 non-null   float64
 6   L6W      1021 non-null   float64
 7   L5W      1016 non-null   float64
 8   L4W      1003 non-null   float64
 9   L3W      999 non-null    float64
 10  L2W      1000 non-null   float64
 11  L1W      994 non-null    float64
 12  L0W      998 non-null    float64
dtypes: float64(9), object(4)
memory usage: 126.3+ KB

Por otro lado, con respecto a la base relacionada con las órdenes, se evidencia que las siguientes variables presentan problemas de tipado:

*  COUNTRY
*  CITY
*  ZONE
*  METRIC

Es decir, son variables que debido a su naturaleza deberían ser categóricas

# **Análisis de valores faltantes**

In [13]:
## Valores faltantes para las variables del dataframe de las métricas
df_metricas_input.isna().sum().sort_values(ascending=False)

L8W_ROLL               113
L6W_ROLL               111
L7W_ROLL               107
L5W_ROLL               106
L4W_ROLL                98
L3W_ROLL                72
L2W_ROLL                55
L1W_ROLL                43
ZONE_PRIORITIZATION      0
METRIC                   0
ZONE                     0
COUNTRY                  0
CITY                     0
ZONE_TYPE                0
L0W_ROLL                 0
dtype: int64

In [12]:
## Valores faltantes para las variables del dataframe de los órdenes
df_raw_orders.isna().sum().sort_values(ascending=False)

L1W        248
L0W        244
L3W        243
L2W        242
L4W        239
L5W        226
L8W        221
L6W        221
L7W        220
METRIC       0
ZONE         0
CITY         0
COUNTRY      0
dtype: int64